version: '3'
services:
  books:
    build:
      context: .
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/books

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
