version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - booknet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  books-service:
    build:
      context: ./books_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - booknet
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      FLASK_ENV: development

networks:
  booknet:
    driver: bridge
