version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - booknet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  books-service:
    build:
      context: ./books_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - booknet
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/
      FLASK_ENV: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]  # Add a health endpoint to your Flask app
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

networks:
  booknet:
    driver: bridge
