version: '3.8'

services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"

  books-service:
    build:
      context: ./books_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mongo
