name: assignment3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./books-service
          file: ./books-service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/books-service:latest

      - name: Save log
        run: echo "image successfully built" >> log.txt

      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/books-service:latest

      - name: Run books service
        run: |
          docker run -d -p 5001:5001 --name books-service ${{ secrets.DOCKER_USERNAME }}/books-service:latest

      - name: Run tests
        run: |
          pytest -v tests/assn3_tests.py > assn3_test_results.txt
          if [ $? -eq 0 ]; then
            echo "tests succeeded" >> log.txt
          else
            echo "tests failed" >> log.txt

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: assn3_test_results.txt

      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt

  query:
    needs: test
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/books-service:latest

      - name: Run books service
        run: |
          docker run -d -p 5001:5001 --name books-service ${{ secrets.DOCKER_USERNAME }}/books-service:latest

      - name: Execute queries
        run: |
          while IFS= read -r query; do
            response=$(curl -s "http://localhost:5001/books$query")
            echo "query: $query" >> response.txt
            echo "response: $response" >> response.txt
          done < query.txt

      - name: Upload query results
        uses: actions/upload-artifact@v2
        with:
          name: response
          path: response.txt

      - name: Upload log
        uses: actions/upload-artifact@v2
        with:
          name: log
          path: log.txt
